version: '3.4'

services:
  dmp-gui-frontend:
    image:   "{{ REGISTRY }}/dmp-gui-frontend:v1.0.0"
    restart: always
    environment:
      - PRODUCT=staging
      - PORT=4000
    ports:
      - 5570:4000
