---

- name: Configure ssh related settings
  hosts: "{{ groups.all }}"
  any_errors_fatal: true
  roles:
    - role: ssh
  tags:
    - ssh

- name: Install docker engine and docker-compose
  hosts: "{{ groups.all }}"
  roles:
    - role: docker
  tags:
    - docker

- name: Update docker-compose.yaml
  hosts: "{{ groups.all }}"
  become: yes
  any_errors_fatal: true
  roles:
    - role: docker-compose
  tags:
    - docker-compose

- name: Install helm
  hosts: "{{ groups.all }}"
  roles:
    - role: gantsign.helm
      vars:
        helm_version: 3.7.2
        helm_architecture: amd64
  tags:
    - helm
